In [1]:
import os
import pandas as pd
pd.set_option('display.max_colwidth', 400)
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
def pretty_print(df):
    return display( HTML( df.to_html().replace("\\n","<br>") ) )
import glob
os.sys.path.insert(0, '../evaluation')
%matplotlib inline

In [8]:
models = [os.path.basename(p) for p in glob.glob(f'../data/models/how_metrics_work/*')]

dfs = [pd.read_csv(f'../data/models/how_metrics_work/{model}/system_evaluation.csv', 
                   index_col=['subset', 'references', 'metric']) for model in models]

df = pd.concat(dfs, keys=models)
df = df.unstack().reset_index(level=[1, 2], drop=True)[[('value', 'bleu'), ('value', 'meteor'), ('value', 'ter')]].sort_values(('value', 'bleu'), ascending=False)
df

                   value
metric              bleu    meteor       ter
delete_4_from_100  97.24  0.718396  0.017056
delete_4_from_200  94.64  0.668297  0.033941
delete100          94.16  0.915135  0.089798
shuffle100         93.36  0.633581  0.064044
repeat100          90.23  0.783842  0.104210
delete_4_from_400  89.26  0.600745  0.067881
delete200          87.63  0.826250  0.181728
shuffle200         85.82  0.574582  0.137127
delete_4_from_600  83.30  0.550446  0.101907
repeat200          82.77  0.742711  0.201043
repeat400          70.96  0.689741  0.397439
delete400          69.96  0.639956  0.366014
shuffle400         68.77  0.505727  0.295361
repeat600          61.38  0.647847  0.614429
shuffle600         50.90  0.463442  0.441656
delete600          43.31  0.436535  0.554265

In [9]:
print(df.to_latex())

\begin{tabular}{lrrr}
\toprule
{} & \multicolumn{3}{l}{value} \\
metric &   bleu &    meteor &       ter \\
\midrule
delete\_4\_from\_100 &  97.24 &  0.718396 &  0.017056 \\
delete\_4\_from\_200 &  94.64 &  0.668297 &  0.033941 \\
delete100         &  94.16 &  0.915135 &  0.089798 \\
shuffle100        &  93.36 &  0.633581 &  0.064044 \\
repeat100         &  90.23 &  0.783842 &  0.104210 \\
delete\_4\_from\_400 &  89.26 &  0.600745 &  0.067881 \\
delete200         &  87.63 &  0.826250 &  0.181728 \\
shuffle200        &  85.82 &  0.574582 &  0.137127 \\
delete\_4\_from\_600 &  83.30 &  0.550446 &  0.101907 \\
repeat200         &  82.77 &  0.742711 &  0.201043 \\
repeat400         &  70.96 &  0.689741 &  0.397439 \\
delete400         &  69.96 &  0.639956 &  0.366014 \\
shuffle400        &  68.77 &  0.505727 &  0.295361 \\
repeat600         &  61.38 &  0.647847 &  0.614429 \\
shuffle600        &  50.90 &  0.463442 &  0.441656 \\
delete600         &  43.31 &  0.436535 &  0.554265 \\
\bottomrule
\end{tabular}